/* Generated by GOB (v2.0.11) on Fri Jul  8 22:48:21 2005
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */


#line 3 "loqui-tray-icon.gob"

/*
 * Loqui -- Chat/IM client for Gtk2 <http://loqui.good-day.net/>
 * Copyright (C) 2002-2003 Yoichi Imai <yoichi@silver-forest.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#line 29 "loqui-tray-icon.c"
#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 11

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "loqui-tray-icon-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 39 "loqui-tray-icon.gob"

#undef G_LOG_DOMAIN
#include "config.h"
#include <glib/gi18n.h>

#include "loqui-tray-icon.h"
#include "loqui_stock.h"
#include "gtkutils.h"

#define LOQUI_TRAY_ICON_BLINK_COUNT 20
#define LOQUI_TRAY_ICON_BLINK_INTERVAL 750

#line 61 "loqui-tray-icon.c"
/* self casting macros */
#define SELF(x) LOQUI_TRAY_ICON(x)
#define SELF_CONST(x) LOQUI_TRAY_ICON_CONST(x)
#define IS_SELF(x) LOQUI_IS_TRAY_ICON(x)
#define TYPE_SELF LOQUI_TYPE_TRAY_ICON
#define SELF_CLASS(x) LOQUI_TRAY_ICON_CLASS(x)

#define SELF_GET_CLASS(x) LOQUI_TRAY_ICON_GET_CLASS(x)

/* self typedefs */
typedef LoquiTrayIcon Self;
typedef LoquiTrayIconClass SelfClass;

/* here are local prototypes */
static void loqui_tray_icon_init (LoquiTrayIcon * o) G_GNUC_UNUSED;
static void loqui_tray_icon_class_init (LoquiTrayIconClass * c) G_GNUC_UNUSED;
static gboolean loqui_tray_icon_button_press_event_cb (GtkWidget * widget, GdkEventButton * event, LoquiTrayIcon * self) G_GNUC_UNUSED;
static void loqui_tray_icon_set_icon (LoquiTrayIcon * self, gboolean is_hilighted) G_GNUC_UNUSED;
static gboolean loqui_tray_icon_blink_for_idle_cb (LoquiTrayIcon * self) G_GNUC_UNUSED;
static gboolean loqui_tray_icon_blink_cb (LoquiTrayIcon * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static EggTrayIconClass *parent_class = NULL;

/* Short form macros */
#define self_button_press_event_cb loqui_tray_icon_button_press_event_cb
#define self_set_icon loqui_tray_icon_set_icon
#define self_blink_for_idle_cb loqui_tray_icon_blink_for_idle_cb
#define self_blink_cb loqui_tray_icon_blink_cb
#define self_new loqui_tray_icon_new
#define self_set_hilighted loqui_tray_icon_set_hilighted
#define self_blink loqui_tray_icon_blink
GType
loqui_tray_icon_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (LoquiTrayIconClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) loqui_tray_icon_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (LoquiTrayIcon),
			0 /* n_preallocs */,
			(GInstanceInitFunc) loqui_tray_icon_init,
			NULL
		};

		type = g_type_register_static (EGG_TYPE_TRAY_ICON, "LoquiTrayIcon", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((LoquiTrayIcon *)g_object_new(loqui_tray_icon_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static LoquiTrayIcon * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static LoquiTrayIcon *
GET_NEW_VARG (const char *first, ...)
{
	LoquiTrayIcon *ret;
	va_list ap;
	va_start (ap, first);
	ret = (LoquiTrayIcon *)g_object_new_valist (loqui_tray_icon_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::finalize"
	LoquiTrayIcon *self G_GNUC_UNUSED = LOQUI_TRAY_ICON (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
}
#undef __GOB_FUNCTION__

static void 
loqui_tray_icon_init (LoquiTrayIcon * o G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::init"
	o->_priv = G_TYPE_INSTANCE_GET_PRIVATE(o,TYPE_SELF,LoquiTrayIconPrivate);
}
#undef __GOB_FUNCTION__
static void 
loqui_tray_icon_class_init (LoquiTrayIconClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	g_type_class_add_private(c,sizeof(LoquiTrayIconPrivate));

	parent_class = g_type_class_ref (EGG_TYPE_TRAY_ICON);

	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__



#line 64 "loqui-tray-icon.gob"
static gboolean 
loqui_tray_icon_button_press_event_cb (GtkWidget * widget, GdkEventButton * event, LoquiTrayIcon * self)
#line 174 "loqui-tray-icon.c"
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::button_press_event_cb"
#line 64 "loqui-tray-icon.gob"
	g_return_val_if_fail (self != NULL, (gboolean )FALSE);
#line 64 "loqui-tray-icon.gob"
	g_return_val_if_fail (LOQUI_IS_TRAY_ICON (self), (gboolean )FALSE);
#line 181 "loqui-tray-icon.c"
{
#line 65 "loqui-tray-icon.gob"
	
        	if (event->type == GDK_BUTTON_PRESS) {
        		switch (event->button) {
        		case 1:
        			if (gtkutils_widget_is_iconified(GTK_WIDGET(self->app)) ||
        			    loqui_app_is_obscured(self->app))
        				gtk_window_present(GTK_WINDOW(self->app));
        			else
        				gtk_window_iconify(GTK_WINDOW(self->app));
        			break;
        		case 3:
        			gtk_menu_popup(GTK_MENU(selfp->menu), NULL, NULL,
        				       gtkutils_menu_position_under_or_below_widget, GTK_WIDGET(self),
        				       event ? event->button : 0,
        				       event ? event->time : gtk_get_current_event_time());
        			break;
        		default:
        			break;
        		}
        	}
        	return FALSE;
        }}
#line 206 "loqui-tray-icon.c"
#undef __GOB_FUNCTION__

#line 88 "loqui-tray-icon.gob"
static void 
loqui_tray_icon_set_icon (LoquiTrayIcon * self, gboolean is_hilighted)
#line 212 "loqui-tray-icon.c"
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::set_icon"
#line 88 "loqui-tray-icon.gob"
	g_return_if_fail (self != NULL);
#line 88 "loqui-tray-icon.gob"
	g_return_if_fail (LOQUI_IS_TRAY_ICON (self));
#line 219 "loqui-tray-icon.c"
{
#line 89 "loqui-tray-icon.gob"
	
        	gtk_image_set_from_stock(GTK_IMAGE(self->image),
        				 is_hilighted ? LOQUI_STOCK_LOQUI_HILIGHTED : LOQUI_STOCK_LOQUI,
        				 GTK_ICON_SIZE_LARGE_TOOLBAR);
        }}
#line 227 "loqui-tray-icon.c"
#undef __GOB_FUNCTION__

#line 95 "loqui-tray-icon.gob"
static gboolean 
loqui_tray_icon_blink_for_idle_cb (LoquiTrayIcon * self)
#line 233 "loqui-tray-icon.c"
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::blink_for_idle_cb"
#line 95 "loqui-tray-icon.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 95 "loqui-tray-icon.gob"
	g_return_val_if_fail (LOQUI_IS_TRAY_ICON (self), (gboolean )0);
#line 240 "loqui-tray-icon.c"
{
#line 96 "loqui-tray-icon.gob"
	
        	g_timeout_add(LOQUI_TRAY_ICON_BLINK_INTERVAL, (GSourceFunc) loqui_tray_icon_blink_cb, self);
        
        	return FALSE;
        }}
#line 248 "loqui-tray-icon.c"
#undef __GOB_FUNCTION__

#line 102 "loqui-tray-icon.gob"
static gboolean 
loqui_tray_icon_blink_cb (LoquiTrayIcon * self)
#line 254 "loqui-tray-icon.c"
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::blink_cb"
#line 102 "loqui-tray-icon.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 102 "loqui-tray-icon.gob"
	g_return_val_if_fail (LOQUI_IS_TRAY_ICON (self), (gboolean )0);
#line 261 "loqui-tray-icon.c"
{
#line 103 "loqui-tray-icon.gob"
	
        	if (selfp->blink_count_remains > 0) {
        		self_set_icon(self, (selfp->blink_count_remains % 2 != 0) ? TRUE : FALSE);
        		selfp->blink_count_remains--;
        		return TRUE;
        	} else {
        		self_set_icon(self, self->is_hilighted);
        		selfp->blinking = FALSE;
        		return FALSE;
        	}
        }}
#line 275 "loqui-tray-icon.c"
#undef __GOB_FUNCTION__

#line 115 "loqui-tray-icon.gob"
GtkWidget * 
loqui_tray_icon_new (LoquiApp * app, GtkMenu * menu)
#line 281 "loqui-tray-icon.c"
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::new"
{
#line 116 "loqui-tray-icon.gob"
	
		Self *self;
        
        	GtkWidget *event_box;
        
        	self = GET_NEW_VARG("title", "Loqui", NULL);
        	
        	self->app = app;
        	selfp->menu = menu;
        
        	event_box = gtk_event_box_new();
        	gtk_container_add(GTK_CONTAINER(self), event_box);
        	
        	g_signal_connect(G_OBJECT(event_box), "button_press_event",
        			 G_CALLBACK(self_button_press_event_cb), self);
        
        	self->image = gtk_image_new_from_stock(LOQUI_STOCK_LOQUI, GTK_ICON_SIZE_LARGE_TOOLBAR);
        	gtk_container_add(GTK_CONTAINER(event_box), self->image);
        
        	self_set_hilighted(self, FALSE);
        	gtk_widget_show_all(GTK_WIDGET(self));
        	
                return GTK_WIDGET(self);
        }}
#line 310 "loqui-tray-icon.c"
#undef __GOB_FUNCTION__

#line 141 "loqui-tray-icon.gob"
void 
loqui_tray_icon_set_hilighted (LoquiTrayIcon * self, gboolean is_hilighted)
#line 316 "loqui-tray-icon.c"
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::set_hilighted"
#line 141 "loqui-tray-icon.gob"
	g_return_if_fail (self != NULL);
#line 141 "loqui-tray-icon.gob"
	g_return_if_fail (LOQUI_IS_TRAY_ICON (self));
#line 323 "loqui-tray-icon.c"
{
#line 142 "loqui-tray-icon.gob"
	
        	if (self->is_hilighted == is_hilighted)
        		return;
        
        	self->is_hilighted = is_hilighted;
        	self_set_icon(self, is_hilighted);
        }}
#line 333 "loqui-tray-icon.c"
#undef __GOB_FUNCTION__

#line 150 "loqui-tray-icon.gob"
void 
loqui_tray_icon_blink (LoquiTrayIcon * self)
#line 339 "loqui-tray-icon.c"
{
#define __GOB_FUNCTION__ "Loqui:Tray:Icon::blink"
#line 150 "loqui-tray-icon.gob"
	g_return_if_fail (self != NULL);
#line 150 "loqui-tray-icon.gob"
	g_return_if_fail (LOQUI_IS_TRAY_ICON (self));
#line 346 "loqui-tray-icon.c"
{
#line 151 "loqui-tray-icon.gob"
	
        	selfp->blink_count_remains = LOQUI_TRAY_ICON_BLINK_COUNT;

        	if (!selfp->blinking) {
        		selfp->blinking = TRUE;
        		g_idle_add((GSourceFunc) self_blink_for_idle_cb, self);
        	}
        }}
#line 357 "loqui-tray-icon.c"
#undef __GOB_FUNCTION__
