/* Generated by GOB (v2.0.11)   (do not edit directly) */



/*
 * Loqui -- Chat/IM client for Gtk2 <http://loqui.good-day.net/>
 * Copyright (C) 2002-2003 Yoichi Imai <yoichi@silver-forest.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include <glib.h>
#include <glib-object.h>
#ifndef __LOQUI_TRAY_ICON_H__
#define __LOQUI_TRAY_ICON_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include "eggtrayicon.h"



#ifndef __TYPEDEF_LOQUI_TRAY_ICON__
#define __TYPEDEF_LOQUI_TRAY_ICON__
typedef struct _LoquiTrayIcon LoquiTrayIcon;
#endif

#include "loqui_app.h"


/*
 * Type checking and casting macros
 */
#define LOQUI_TYPE_TRAY_ICON	(loqui_tray_icon_get_type())
#define LOQUI_TRAY_ICON(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), loqui_tray_icon_get_type(), LoquiTrayIcon)
#define LOQUI_TRAY_ICON_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), loqui_tray_icon_get_type(), LoquiTrayIcon const)
#define LOQUI_TRAY_ICON_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), loqui_tray_icon_get_type(), LoquiTrayIconClass)
#define LOQUI_IS_TRAY_ICON(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), loqui_tray_icon_get_type ())

#define LOQUI_TRAY_ICON_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), loqui_tray_icon_get_type(), LoquiTrayIconClass)

/* Private structure type */
typedef struct _LoquiTrayIconPrivate LoquiTrayIconPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_LOQUI_TRAY_ICON__
#define __TYPEDEF_LOQUI_TRAY_ICON__
typedef struct _LoquiTrayIcon LoquiTrayIcon;
#endif
struct _LoquiTrayIcon {
	EggTrayIcon __parent__;
	/*< public >*/
	GtkWidget * image;
	gboolean is_hilighted;
	LoquiApp * app;
	/*< private >*/
	LoquiTrayIconPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _LoquiTrayIconClass LoquiTrayIconClass;
struct _LoquiTrayIconClass {
	EggTrayIconClass __parent__;
};


/*
 * Public methods
 */
GType	loqui_tray_icon_get_type	(void);
GtkWidget * 	loqui_tray_icon_new	(LoquiApp * app,
					GtkMenu * menu);
void 	loqui_tray_icon_set_hilighted	(LoquiTrayIcon * self,
					gboolean is_hilighted);
void 	loqui_tray_icon_blink	(LoquiTrayIcon * self);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
